name: Aprendiendo Github Actions
run-name: Estoy aprendiendo Github Actions
on : [push]
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Definir Variable
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      - name: Ejecutar Script
        run: python hola-mundo.py